[package]
name = "rubra"
version = "0.1.0"
edition = "2021"

[dependencies]
adblock = "0.9.1"
gtk4 = "0.9.2"
lazy_static = "1.5.0"
regex = "1.11.0"
url = "2.5.2"
urlencoding = "2.1.3"
webkit6 = "0.4.0"
webkit6-sys = "0.4.0"
