[package]
name = "rubra"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.9.2"
lazy_static = "1.5.0"
regex = "1.11.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
url = "2.5.2"
urlencoding = "2.1.3"
webkit6 = "0.4.0"
webkit6-sys = "0.4.0"
